// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// NOTE: All platforms configured with real Firebase project 'pulsepath-db381' credentials.
// Web authentication should now work properly across all platforms.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCUIgitFWkH4hOqh-nZtM-bD2XAv1I08s',
    appId: '1:22135956583:web:73e54ef3ef7745d19ba0c2',
    messagingSenderId: '22135956583',
    projectId: 'pulsepath-db381',
    authDomain: 'pulsepath-db381.firebaseapp.com',
    storageBucket: 'pulsepath-db381.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JZv5aUTSM1N_TEBw6wI1HR3KdoRCL7s',
    appId: '1:22135956583:android:96719e4e39ba386a9ba0c2',
    messagingSenderId: '22135956583',
    projectId: 'pulsepath-db381',
    storageBucket: 'pulsepath-db381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7O9dCT_cV00MhGulUU_4h2bxC5A23kZ0',
    appId: '1:22135956583:ios:900336e4e50249da9ba0c2',
    messagingSenderId: '22135956583',
    projectId: 'pulsepath-db381',
    storageBucket: 'pulsepath-db381.firebasestorage.app',
    iosBundleId: 'com.pulsepath.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7O9dCT_cV00MhGulUU_4h2bxC5A23kZ0',
    appId: '1:22135956583:ios:900336e4e50249da9ba0c2',
    messagingSenderId: '22135956583',
    projectId: 'pulsepath-db381',
    storageBucket: 'pulsepath-db381.firebasestorage.app',
    iosBundleId: 'com.pulsepath.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCUIgitFWkH4hOqh-nZtM-bD2XAv1I08s',
    appId: '1:22135956583:web:73e54ef3ef7745d19ba0c2',
    messagingSenderId: '22135956583',
    projectId: 'pulsepath-db381',
    authDomain: 'pulsepath-db381.firebaseapp.com',
    storageBucket: 'pulsepath-db381.firebasestorage.app',
  );
}